spring:
  application:
    name: EcoPathAPI

  open:
    route:
      url: https://api.heigit.org/openrouteservice/v2/directions/foot-walking
      token: ${ORS_TOKEN}
    meteo:
      url: https://api.open-meteo.com/v1/forecast
    air:
      url: https://air-quality-api.open-meteo.com/v1/air-quality


  datasource:
    url: jdbc:postgresql://localhost:5440/ecopath_db
    username: postgres
    password: 123456
    driver: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  api:
    security:
      token:
        secret=${JWT_SECRET}:
